### ISSUE TITLE
isLess vs isGreater perofrmance difference

### ISSUE THREAD

**Issue by agdavydov81** [epam/DFP#39]
There is a notable difference in performance of the isLess and isGreater native call for the .NET and Java calls.

**Comment by ruzrobert** [comment]
Hi @agdavydov81 !
Thank you for sharing the code of this project!

Is this issue fixed by the way? Any plans to fix it? Thank you

**Comment by agdavydov81** [comment]
Hi @ruzrobert !
You are welcome! :)

Unfortunately, this issue is not fixed yet.
As this issue is not critical, the priority of it is relatively low.
So, no plans when this issue will be researched.

**Comment by agdavydov81** [comment]
Fixed in d8fb3cebc75005574309dad7568b42c9f9e3231d
Date: 03.02.2023 11:51:23

The benchmark on my platform do not showed significant difference prior this fix.
But this fix gives a slight (about 5-8%) speedup to the Decimal64Utils.compareTo function.
